"""Plan -> runnable pytest + Playwright source.

The generator prefers locators the agent has already *proven* on a live page
(from :class:`Memory`), falling back to the top of the static candidate ladder.
That is the difference between generated code that works and generated code
that merely looks plausible.

Every emitted file is parsed with :mod:`ast` and scanned against an import and
call allowlist before it is written. Code produced by a language model is
untrusted input, and treating it that way is not optional.
"""

from __future__ import annotations

import ast
import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from ..browser.locators import LocatorCandidate, build_candidates
from ..schema import ELEMENT_ACTIONS, Step, TestPlan
from .memory import Memory, scope_for

ALLOWED_IMPORTS = {"re", "os", "json", "time", "pytest", "playwright", "playwright.sync_api", "pathlib"}
BANNED_CALLS = {"eval", "exec", "compile", "__import__", "input", "breakpoint"}
BANNED_ATTRS = {"system", "popen", "spawn", "spawnl", "check_output", "call", "run"}
BANNED_MODULES = {"subprocess", "socket", "shutil", "requests", "urllib", "httpx", "ctypes", "pickle"}


class UnsafeGeneratedCode(ValueError):
    """The generated module failed validation and was not written to disk."""


@dataclass
class GeneratedTest:
    __test__ = False

    name: str
    code: str
    path: Path | None = None
    locators: list[str] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.locators is None:
            self.locators = []


def validate_code(code: str) -> None:
    """Parse and lint generated source. Raises :class:`UnsafeGeneratedCode`."""
    try:
        tree = ast.parse(code)
    except SyntaxError as exc:
        raise UnsafeGeneratedCode(f"generated code does not parse: {exc}") from exc

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".")[0]
                if root in BANNED_MODULES or alias.name not in ALLOWED_IMPORTS and root not in ALLOWED_IMPORTS:
                    raise UnsafeGeneratedCode(f"import of {alias.name!r} is not allowed")
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            root = module.split(".")[0]
            if root in BANNED_MODULES or (module not in ALLOWED_IMPORTS and root not in ALLOWED_IMPORTS):
                raise UnsafeGeneratedCode(f"import from {module!r} is not allowed")
        elif isinstance(node, ast.Call):
            func = node.func
            if isinstance(func, ast.Name) and func.id in BANNED_CALLS:
                raise UnsafeGeneratedCode(f"call to {func.id}() is not allowed")
            if isinstance(func, ast.Attribute) and func.attr in BANNED_ATTRS:
                if isinstance(func.value, ast.Name) and func.value.id in {"os", "subprocess"}:
                    raise UnsafeGeneratedCode(f"call to {func.value.id}.{func.attr}() is not allowed")


def _py_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


class TestGenerator:
    __test__ = False  # generates tests, is not one

    def __init__(self, settings, memory: Memory | None = None) -> None:
        self.settings = settings
        self.memory = memory

    # ------------------------------------------------------------------
    def _locator_code(self, description: str, action: str, scope: str) -> tuple[str, str]:
        known: Sequence[str] = ()
        if self.memory is not None:
            known = self.memory.known_keys(description, scope)
        candidates = build_candidates(description, action, known=known)
        if not candidates:
            candidates = [LocatorCandidate("text", description, strategy="visible-text")]

        if known:
            # Proven on a real page during a run: emit exactly that.
            best = candidates[0]
        else:
            # Nothing proven yet. A speculative [data-testid="..."] is a coin
            # flip, while role/label/placeholder are derived from the words the
            # author already used, so they are far likelier to bind.
            best = next(
                (c for c in candidates if c.kind in {"role", "label", "placeholder", "text"}),
                candidates[0],
            )
        return best.code("page"), f"{best.strategy}:{best.describe()}"

    # ------------------------------------------------------------------
    def generate(self, plan: TestPlan) -> GeneratedTest:
        base = plan.base_url or self.settings.app.base_url
        lines: list[str] = []
        used: list[str] = []
        scope = "/"

        header = [
            '"""Generated by ForkableAIAgent - do not edit by hand.',
            "",
            f"Plan: {plan.name}",
            f"Source: {plan.source}",
            f"Spec: {(plan.description or '').strip()[:150]}",
            "",
            "Regenerate with:  forkable generate --spec <file>",
            '"""',
            "",
            "import re",
            "",
            "import pytest",
            "from playwright.sync_api import Page, expect",
            "",
            f"BASE_URL = {_py_str(base)}",
            "",
            "",
            "@pytest.mark.forkable",
            f"def test_{plan.name}(page: Page) -> None:",
        ]

        for step in plan.steps:
            code_lines, scope, locator_note = self._step_code(step, scope)
            lines.extend(code_lines)
            if locator_note:
                used.append(locator_note)

        if len(lines) == 0:
            lines.append("    pass")

        code = "\n".join(header + lines) + "\n"
        validate_code(code)
        return GeneratedTest(name=plan.name, code=code, locators=used)

    # ------------------------------------------------------------------
    def _step_code(self, step: Step, scope: str) -> tuple[list[str], str, str]:
        action = step.action
        note = ""
        out: list[str] = []
        if step.note:
            out.append(f"    # {step.note}")

        if action == "goto":
            target = step.target or "/"
            scope = scope_for(target)
            if target.startswith(("http://", "https://")):
                out.append(f"    page.goto({_py_str(target)})")
            else:
                out.append(f'    page.goto(f"{{BASE_URL}}{target if target.startswith("/") else "/" + target}")')
            return out, scope, note

        if action == "wait":
            seconds = float(step.value or "1")
            out.append(f"    page.wait_for_timeout({int(seconds * 1000)})")
            return out, scope, note

        if action == "screenshot":
            name = step.value or "screenshot"
            out.append(f'    page.screenshot(path={_py_str(f".forkable/artifacts/{name}.png")})')
            return out, scope, note

        if action == "visual_check":
            # Nested same-quote f-strings are a syntax error before 3.12, so
            # build the path first rather than inlining it.
            name = step.value or "page"
            out.append(f"    # visual baseline check '{name}' runs through the agent runtime")
            out.append(f'    page.screenshot(path={_py_str(f".forkable/artifacts/{name}.png")})')
            return out, scope, note

        if action == "expect_url":
            out.append(f"    expect(page).to_have_url(re.compile({_py_str(re.escape(step.value))}))")
            return out, scope, note

        if action == "expect_title":
            out.append(f"    expect(page).to_have_title(re.compile({_py_str(re.escape(step.value))}, re.I))")
            return out, scope, note

        if action == "expect_text":
            out.append(f'    expect(page.locator("body")).to_contain_text({_py_str(step.value)})')
            return out, scope, note

        if action == "expect_no_text":
            out.append(f'    expect(page.locator("body")).not_to_contain_text({_py_str(step.value)})')
            return out, scope, note

        if action in ELEMENT_ACTIONS:
            locator, note = self._locator_code(step.target, action, scope)
            if action == "click":
                out.append(f"    {locator}.click()")
            elif action == "fill":
                out.append(f"    {locator}.fill({_py_str(step.value)})")
            elif action == "press":
                out.append(f"    {locator}.press({_py_str(step.value or 'Enter')})")
            elif action == "check":
                out.append(f"    {locator}.check()")
            elif action == "uncheck":
                out.append(f"    {locator}.uncheck()")
            elif action == "hover":
                out.append(f"    {locator}.hover()")
            elif action == "select":
                out.append(f"    {locator}.select_option({_py_str(step.value)})")
            elif action == "expect_visible":
                out.append(f"    expect({locator}).to_be_visible()")
            elif action == "expect_value":
                out.append(f"    expect({locator}).to_have_value(re.compile({_py_str(re.escape(step.value))}, re.I))")
            return out, scope, note

        out.append(f"    # unsupported action: {action}")
        return out, scope, note

    # ------------------------------------------------------------------
    def write(self, generated: GeneratedTest, out_dir: str | Path) -> Path:
        directory = Path(out_dir)
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / f"test_{generated.name}.py"
        path.write_text(generated.code, encoding="utf-8")
        generated.path = path
        return path
